### ISSUE TITLE
Cannot find module '@typescript-eslint/parser'

### ISSUE THREAD

**Issue by tewarid** [standard/semistandard#249]
**What version of this package are you using?**

Version 14.0.1. Works with version 13.0.1.

**What operating system, Node.js, and npm version?**

Node version 10.16.3 in docker lts-alpine image

**What happened?**

Running standard as described at https://tewarid.github.io/2019/08/01/use-semistandard-to-lint-typescript-code.html is resulting in the following error

```
semistandard: Unexpected linter output:

Error: Failed to load parser '@typescript-eslint/parser' declared in 'CLIOptions': Cannot find module '@typescript-eslint/parser'
Require stack:
- /__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Object.resolve (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadParser (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/cli-engine/config-array-factory.js:752:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/cli-engine/config-array-factory.js:550:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.create (/usr/local/lib/node_modules/semistandard/node_modules/eslint/lib/cli-engine/config-array-factory.js:362:16)
```

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment]
- Can you print the output of `npm ls @typescript-eslint/parser`?
- Are you using npm or an alternate package manager? Which version?

**Comment by tewarid** [comment]
```
/ # npm ls -g @typescript-eslint/parser
/usr/local/lib
`-- @typescript-eslint/parser@2.0.0 

/ # npm --version
6.9.0
```

**Comment by feross** [comment]
I believe that you need to install the parser locally in your project. The new version of ESLint no longer looks for global plugins.

> If you use a global installation of ESLint (e.g. installed with npm install eslint --global) along with plugins, you should install those plugins locally in the projects where you run ESLint.

See: https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification

**Comment by Its-Shashank** [comment]
> * Can you print the output of `npm ls @typescript-eslint/parser`?
> * Are you using npm or an alternate package manager? Which version?

Output I get here is (empty).

**Comment by margotpaon** [comment]
@Its-Shashank try yarn add @typescript-eslint/parser -d
